// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vmag.cpp"
#include "Vmag___024root__0.cpp"
#include "Vmag__ConstPool__0__Slow.cpp"
#include "Vmag___024root__Slow.cpp"
#include "Vmag___024root__0__Slow.cpp"
#include "Vmag__Syms__Slow.cpp"
